#!/bin/bash

# Branch Protection Setup Script
# This script guides you through setting up branch protection for the master branch

echo "🔒 Branch Protection Setup for my-portfolio-menno"
echo "================================================="
echo ""

echo "📋 Current Repository Status:"
echo "Repository: mdresch/my-portfolio-menno"
echo "Primary Branch: master"
echo "Test Suite: 88 comprehensive tests available"
echo ""

echo "🎯 Branch Protection Configuration Steps:"
echo ""
echo "1. Open your repository in GitHub:"
echo "   https://github.com/mdresch/my-portfolio-menno"
echo ""
echo "2. Navigate to Settings > Branches"
echo ""
echo "3. Click 'Add rule' and configure as follows:"
echo ""
echo "   Branch name pattern: master"
echo ""
echo "   ✅ Require a pull request before merging"
echo "      - Required number of approvals: 1"
echo "      - ✅ Dismiss stale pull request approvals when new commits are pushed"
echo ""
echo "   ✅ Require status checks to pass before merging"
echo "      - ✅ Require branches to be up to date before merging"
echo "      - Status checks to require (add these after first CI run):"
echo "        • test"
echo "        • lint"
echo "        • build"
echo "        • auto-requirements-test"
echo ""
echo "   ✅ Include administrators"
echo "   ❌ Allow force pushes (leave unchecked)"
echo "   ❌ Allow deletions (leave unchecked)"
echo ""
echo "4. Click 'Create' to save the protection rules"
echo ""

echo "🚀 Next Steps:"
echo "1. Commit and push the CI workflow we've created"
echo "2. The first workflow run will establish the status checks"
echo "3. Test the protection by attempting a direct push (should fail)"
echo "4. Create a feature branch and test the PR workflow"
echo ""

echo "🧪 Testing Commands:"
echo ""
echo "# Test direct push (should fail after protection is enabled):"
echo "git checkout master"
echo "echo '# Test' >> test-protection.md"
echo "git add test-protection.md"
echo "git commit -m 'Test direct push'"
echo "git push origin master  # This should fail"
echo ""
echo "# Test PR workflow:"
echo "git checkout -b feature/test-branch-protection"
echo "echo '# Branch protection test' >> test-feature.md"
echo "git add test-feature.md"
echo "git commit -m 'Test PR workflow'"
echo "git push origin feature/test-branch-protection"
echo "gh pr create --title 'Test: Branch Protection' --body 'Testing the new branch protection rules'"
echo ""

echo "📚 Documentation created:"
echo "- docs/BRANCH_PROTECTION_SETUP.md - Detailed setup guide"
echo "- .github/workflows/ci.yml - CI/CD pipeline for status checks"
echo ""

echo "Ready to proceed? The CI workflow and documentation are prepared for commit."
